db = ".findx/catalog.db"
tantivy_index = ".findx/idx"
roots = ["."]
include = ["**/*.pdf", "**/*.docx", "**/*.md", "**/*.txt"]
exclude = ["**/.git/**", "**/~$*"]
max_file_size_mb = 200
follow_symlinks = false
commit_interval_secs = 45
guard_interval_secs = 180
default_language = "auto"
extractor_cmd = "docling --to text"

[embedding]
provider = "disabled"

[mirror]
root = ".findx/raw"

[bus.bounds]
source_fs = 1024
mirror_text = 1024

[extract]
pool_size = 4

