db = ".findx/catalog.db"
tantivy_index = ".findx/idx"
roots = ["."]
include = ["**/*.pdf", "**/*.docx", "**/*.md", "**/*.txt"]
exclude = ["**/.git/**", "**/~$*"]
max_file_size_mb = 200
follow_symlinks = false
commit_interval_secs = 45
guard_interval_secs = 180
default_language = "auto"
extractor_cmd = "docling --to txt"

[embedding]
provider = "disabled"

