name: release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_name: linux
            ext: ""
          - os: macos-latest
            os_name: macos
            ext: ""
          - os: windows-latest
            os_name: windows
            ext: ".exe"
    steps:
      - uses: actions/checkout@v4

      - name: Compute version metadata
        id: meta
        shell: bash
        run: .github/scripts/version.sh

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        env:
          FINDX_VERSION: ${{ steps.meta.outputs.version }}
        run: cargo build --release

      - name: Package
        id: pkg
        shell: bash
        run: |
          ARCH=x86_64
          OS=${{ matrix.os_name }}
          NAME="findx_${OS}_${ARCH}_${{ steps.meta.outputs.version }}"
          mkdir -p "pkg/$NAME"
          cp LICENSE README.md target/release/findx${{ matrix.ext }} "pkg/$NAME"/
          echo "dir=pkg/$NAME" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pkg.outputs.name }}
          path: ${{ steps.pkg.outputs.dir }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dl
      - name: Repack & checksums
        shell: bash
        run: |
          mkdir -p out
          for d in dl/*; do
            base=$(basename "$d")
            if [[ "$base" == *windows* ]]; then
              (cd dl && zip -r -9 "../out/${base}.zip" "$base")
            else
              tar -C dl -czf "out/${base}.tar.gz" "$base"
            fi
          done
          (cd out && sha256sum * > SHA256SUMS.txt)
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
